apiVersion: v1
kind: Service
metadata:
  name: eks-linux-service
  namespace: eks-app
  labels:
    app: eks-linux-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: eks-linux-app