apiVersion: v1
kind: Service
metadata:
  name: eks-linux-service
  namespace: eks-app
  labels:
    app: eks-linux-app
spec:
  selector:
    app: eks-linux-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080