name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build -t idsfinal .
      - name: Push the Docker image
        run: docker tag idsfinal ${{ secrets.DOCKER_USERNAME }}/idsfinal:latest

  # test:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: rust:latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run tests
  #       run: RUST_BACKTRACE=full cargo test --bin ids721-final

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: '1.21.0'
      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/deployment.yaml
      - name: Deploy service
        run: kubectl apply -f k8s/service.yaml

  
