name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build -t idsfinal .
      - name: Push the Docker image
        run: docker tag idsfinal ${{ secrets.DOCKER_USERNAME }}/idsfinal:latest

  # test:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   container:
  #     image: rust:latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Setup Rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         profile: minimal
  #         override: true

  #     - name: Setup Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.9'

  #     - name: Install Python dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install transformers torch
  #     - uses: actions/checkout@v3
  #     - name: Run tests
  #       run: RUST_BACKTRACE=full cargo test --bin ids721-final

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
        - uses: actions/checkout@v3
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - name: Install Python dependencies
          run: |
            python -m pip install --upgrade pip
            pip install transformers torch
        - name: Install Minikube
          run: |
            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            sudo install minikube-linux-amd64 /usr/local/bin/minikube
        - name: Install kubectl
          run: |
            curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
        - name: Start Minikube
          run: |
            minikube start --driver=none
        - name: Set KUBECONFIG
          run: |
            echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
        - name: Check Minikube status
          run: |
            minikube status
        - name: Deploy to Kubernetes
          run: |
            kubectl apply -f k8s/deployment.yaml
        - name: Deploy service
          run: |
            kubectl apply -f k8s/service.yaml
